### ISSUE TITLE
Upgrade for Elasticsearch 2.0.0

### ISSUE THREAD

**Issue by damm** [sensu-plugins/sensu-plugins-elasticsearch#11]
Check failed to run: undefined method `[]' for 0.13:Float, ["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-elasticsearch-0.2.0/bin/metrics-es-node-graphite.rb:169:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by multani** [comment]
The ``check-es-node-status.rb`` check also always fails now. (it always returns ``ESNodeStatus CRITICAL: Dead (0)``)

**Comment by eheydrick** [comment]
@damm the node stats API changed in ES 2.0. load average is no longer an array, network stats are gone, and uptime is now under jvm. I updated the plugin for the new API, can you test it out. https://github.com/eheydrick/sensu-plugins-elasticsearch/blob/es_2.0/bin/metrics-es-node-graphite.rb

I ran it on ES 1.7 and 2.0 and it outputs stats on both versions.

**Comment by eheydrick** [comment]
@multani the problem with check-es-node-status.rb is that ES 2.0 no longer returns status from /. Looking to see if it moved to a different endpoint or we need to grab status some other way.

**Comment by eheydrick** [comment]
check-es-node-status works with ES 2.0 with https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/14.
